### ISSUE TITLE
Just coming here and say Hi.

### ISSUE THREAD

**Issue by Umpire2018** [nalbion/intellij-ai-agent-client#2]
Hi, nalbion

I am a junior Python engineer and I find open-source projects very intriguing. I came across your contributions in GPT-Pilot and thought I'd reach out to see if there's anything I can assist you with.

By studying and contributing to projects involving ai agents, I aim to enhance my understanding of their effective interaction, communication, and coordination. This knowledge will not only improve my Python engineering skills but also provide insights into designing harmoniously working intelligent systems.

**Comment by nalbion** [comment]
Hey @Umpire2018 sure, it would be great to have some help. I've gone through the issues list and labelled some as "Good first issue"

https://github.com/Pythagora-io/gpt-pilot/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
